language: java

jdk:
- oraclejdk7

env: 
  global: 
  - RELEASE_CANDIDATE=$(.travis.d/release_candidate.sh)
  - secure: "bbuXX0WsP2DX6rb9gXvlkyYr+Za8rvMx+SBgCODuao8JGy8PyDPgnJzVV4i85+1YvKx2iGv0//fN646VelJbXSdyGNzVx+JRjS6rdR43rZj1WA3+T2mwoKDaKcXruKLt6XmuHIBA69G+4PWVMjEqShE2dpiV8VnBib+FMeK/grw="

script:
- .travis.d/script.sh

after_success:
- .travis.d/after_success.sh
