language: java

jdk:
- oraclejdk7

before_install:
- openssl aes-256-cbc -K $encrypted_4269c1dbcc16_key -iv $encrypted_4269c1dbcc16_iv
  -in .travis.d/secret.tar.enc -out .travis.d/secret.tar -d

script:
- .travis.d/script.sh

after_success:
- .travis.d/after_success.sh
